project:
  type: book
  output-dir: ../docs/notes_output  # â† important

book:
  title: "Alex Meng's Notes"
  author: "Alex Meng"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  navbar:
    left:
      - text: ğŸ”™ Home
        href: https://yankunm.github.io/

bibliography: references.bib

format:
  html:
    theme: simplex
  pdf:
    documentclass: scrreprt



